### PR TITLE
Sweets/erc20 access control

### PR DESCRIPTION
**Pull request by sweetmantech**
# ERC20 Access Control
- `ERC20AccessControl.sol` - AccessControl Mechanism for ANY quantity of ERC20 token. ✨ 
- `ERC20AccessControl.t.sol` - Unit Tests for `Curator`, `Manager` & `Admin` levels of curation. 🧪 
- `ERC20MinBalAccessControl.sol` - AccessControl Mechanism for Minimum Balance of ERC20 token. ✨ 
- `ERC20MinBalAccessControl.t.sol` - Unit Tests for `Curator`, `Manager` & `Admin` levels of curation with Minimum Balance. 🧪

### CODE REVIEW

**Review by 0xTranqui — CHANGES_REQUESTED** [review]
Erc20AccessControl.sol:

comments starting on line 64 refer to ERC721s, not ERC20s

line 65 function should be called "updateCuratorAccess" -- this is an error in the original one I did for ERC721 that ill be updating. need to fix that and then wtv additional calls/tests refer to that function

Erc20MinBalAccessControl.sol:

same issue with comments refered to above^

line 178 looks like u are hardcoding starting values for min balance in this. is this on purpose? feel like u should just update the initializeWithData call to also let u pass in the min balances for maximum flexibility

line 215 I believe the way ur checking to see if user has appopriate balance is not optimized -- have read before to avoid greater/less than or equal checks in solidity whenever possible (cuz its actually 2 checks not just one). the way u can get around this is just by sending the min balance one point lower, and changing the check to just a "greater than" comparison. it might look counter intuitive but will save gas I believe

ex: for times when u need to make sure things are greater than 0, you can do a "!= 0 check", and for times when u need to make sure things are greater than or equal to X, you can do a "> X-1" check

tests:

not gonna review them rn, but assuming stuff was looking good on ur end. well need to add tests for all of the admin update functions as well

general:

imo you should just push one of these (to try and keep the optionality we're providing as clean/least cluttered as possible) -- and my vote would be for the one with the minimum balance as the default (u could just give that one the name of Erc20AccessControl, and the default functionality includes the min balance check -- which I think makes sense specifically for ERC20s)

random:

do you think we should capitalize ERC in these contract names? not sure

**Comment by sweetmantech** [comment]
Addressed Partial Comments ✅ 
### Erc20AccessControl.sol:

- comments starting on line 64 now refer to `ERC20`s ✅ 
- line 65 function called `updateCuratorAccess` -- this is an error in the original one I did for ERC721 that ill be updating. ✅ 
- updated calls/tests referring to `updateCuratorAccess` function. ✅

**Comment by sweetmantech** [comment]
Addressed Partial Feedback ✅ 

### ERC20MinBalAccessControl.sol:
- comments starting on line 64 now refer to ERC20s ✅
- line 65 function called updateCuratorAccess -- this is an error in the original one I did for ERC721 that ill be updating. ✅
- updated calls/tests referring to updateCuratorAccess function. ✅
- replaced `>=` with `>` to save gas. ✅ 

### Both ERC20 contracts
- refactor contract names from `Erc20` => `ERC20`. ✅

**Comment by sweetmantech** [comment]
addressed all comments except 1 :
## Comment still unaddressed:
- line 178 looks like u are hardcoding starting values for min balance in this. is this on purpose? feel like u should just update the initializeWithData call to also let u pass in the min balances for maximum flexibility
### Reason Unaddressed
- @0xTranqui design shows `initializeAccessControl` being called from shared `Curator` contract. This means all AccessControl modules will need to have same params right? 💭 
Screen Shot 2022-10-30 at 5 41 08 PM

**Comment by 0xTranqui** [comment]
@SweetmanTech after going through the integration updates for the curation protocol, this issue is actually only one with the way I set up mockCurator in these tests, but not reflective of how initialization will work in the real contracts.

similarly to how you can pass in an optional "bytes rendererInitializer" param in the current curation protocol, you will also be able to pass in an optional 'bytes accessControlInitializer" param in the updated version.

its then on the user to make sure that the bytes initializer they pass in is compatible with the accessControl contract they specified

this DOES mean that our tests our outdated in this repo tho, so we should update the tests in here as well to reflect the reality of how the curation contracts work. another thing to add to the list

**Review by 0xTranqui — APPROVED** [review]

**Pull request merged**
