### PR TITLE
deployed to base and updated script a bit

### PR DESCRIPTION
**Pull request by 0xTranqui**

### CODE REVIEW

**Comment by 0xTranqui** [comment]
@salieflewis @hardyjosh just ran the script to deploy this to base (chain Id 8453) and successfully deployed the contract to address [0x8d1F906C58E8e1c2160dE8542466e59a4c336C05](https://base.blockscout.com/address/0x8d1F906C58E8e1c2160dE8542466e59a4c336C05?tab=internal_txns), which annoyingly is not the same detemrinistic address as we have deployed on other chains ([0x9a23AE640040e4d34E9e00E500003000017144F4](https://testnet.explorer.zora.energy/address/0x9a23AE640040e4d34E9e00E500003000017144F4)). any ideas as to why? 

will wait to merge until i get your common sense on it

**Comment by hardyjosh** [comment]
Ah yeah I mentioned I had the same issue, so I had to do this:

```solidity
import {console2} from "forge-std/console2.sol";
import {PlatformThemeRegistry} from "../src/PlatformThemeRegistry.sol";
import {ScriptBase} from "./ScriptBase.sol";
import {stdJson} from "forge-std/stdJson.sol";

contract DeployCore is ScriptBase {
    using stdJson for string;
    function run() public {
        setUp();
        string memory root = vm.projectRoot();
        string memory path = string.concat(root, "/script/run-latest.json");
        string memory json = vm.readFile(path);
        bytes memory creationCode = json.readBytes(".transactions[0].arguments[1]");
        console2.logBytes32(keccak256(creationCode));
        bytes32 salt = bytes32(0x00000000000000000000000000000000000000004757574f055940000019129c);
        vm.broadcast(deployer);
        IMMUTABLE_CREATE2_FACTORY.safeCreate2(salt, creationCode);
    }
}
```

Basically, grab the creation code from one of the previous runs where the newly created address was correct.

I'm not sure exaclty what happened, I assume something changed in the code or compilation between the previous deploys and now, which means the creation code is slightly different (and therefore a different address).

I can put up another PR with this change if you like @0xTranqui ?

**Comment by 0xTranqui** [comment]
thanks for the tip on this. am trying to get this up myself but running into the error:

"...code/base-themeRegistryDeploy-230808/theme-registry/script/run-latest.json" is not allowed to be accessed for read operations."

did you have do something to your foundry settings to enable this type of read?

**Comment by hardyjosh** [comment]
Ah yeah, add this to your foundry.toml

`fs_permissions = [{ access = "read", path = "./"}]`

so

```toml
[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 500000
fs_permissions = [{ access = "read", path = "./"}]
```

**Comment by 0xTranqui** [comment]
got it sorted @hardyjosh !! thanks so much

**Pull request merged**
